//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteGuide.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RouteGuide.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на принять.
        /// </summary>
        public static string ApplicationBarAccept {
            get {
                return ResourceManager.GetString("ApplicationBarAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отменить.
        /// </summary>
        public static string ApplicationBarCancel {
            get {
                return ResourceManager.GetString("ApplicationBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route guide.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все необходимые поля заполнены.
        /// </summary>
        public static string AuthenticationEmptyError {
            get {
                return ResourceManager.GetString("AuthenticationEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин:.
        /// </summary>
        public static string AuthenticationEnterLogin {
            get {
                return ResourceManager.GetString("AuthenticationEnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        public static string AuthenticationEnterPass {
            get {
                return ResourceManager.GetString("AuthenticationEnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход с помощью.
        /// </summary>
        public static string AuthenticationEnterTitle {
            get {
                return ResourceManager.GetString("AuthenticationEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, подождите....
        /// </summary>
        public static string AuthenticationProgressText {
            get {
                return ResourceManager.GetString("AuthenticationProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите с помощью своего аккаунта социальной сети.
        /// </summary>
        public static string AuthenticationTitle {
            get {
                return ResourceManager.GetString("AuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в избранное.
        /// </summary>
        public static string MainPageAppBarFavoriteText {
            get {
                return ResourceManager.GetString("MainPageAppBarFavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на слои.
        /// </summary>
        public static string MainPageAppBarLayersText {
            get {
                return ResourceManager.GetString("MainPageAppBarLayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на где я.
        /// </summary>
        public static string MainPageAppBarLocationText {
            get {
                return ResourceManager.GetString("MainPageAppBarLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на поиск.
        /// </summary>
        public static string MainPageAppBarSearchText {
            get {
                return ResourceManager.GetString("MainPageAppBarSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на о программе.
        /// </summary>
        public static string MainPageMenuAbout {
            get {
                return ResourceManager.GetString("MainPageMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на моя учетная запись.
        /// </summary>
        public static string MainPageMenuAccount {
            get {
                return ResourceManager.GetString("MainPageMenuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на избранное.
        /// </summary>
        public static string MainPageMenuFavorite {
            get {
                return ResourceManager.GetString("MainPageMenuFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на история.
        /// </summary>
        public static string MainPageMenuHistory {
            get {
                return ResourceManager.GetString("MainPageMenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мои особые места.
        /// </summary>
        public static string MainPageMenuPlaces {
            get {
                return ResourceManager.GetString("MainPageMenuPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на метки рядом со мной.
        /// </summary>
        public static string MainPageMenuPoi {
            get {
                return ResourceManager.GetString("MainPageMenuPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оставить отзыв.
        /// </summary>
        public static string MainPageMenuRespect {
            get {
                return ResourceManager.GetString("MainPageMenuRespect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на настройки.
        /// </summary>
        public static string MainPageMenuSettings {
            get {
                return ResourceManager.GetString("MainPageMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мои треки.
        /// </summary>
        public static string MainPageMenuTracks {
            get {
                return ResourceManager.GetString("MainPageMenuTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-ru.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
