//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteGuide.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RouteGuide.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на принять.
        /// </summary>
        public static string ApplicationBarAccept {
            get {
                return ResourceManager.GetString("ApplicationBarAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отменить.
        /// </summary>
        public static string ApplicationBarCancel {
            get {
                return ResourceManager.GetString("ApplicationBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route guide.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все необходимые поля заполнены.
        /// </summary>
        public static string AuthenticationEmptyError {
            get {
                return ResourceManager.GetString("AuthenticationEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин:.
        /// </summary>
        public static string AuthenticationEnterLogin {
            get {
                return ResourceManager.GetString("AuthenticationEnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        public static string AuthenticationEnterPass {
            get {
                return ResourceManager.GetString("AuthenticationEnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход с помощью.
        /// </summary>
        public static string AuthenticationEnterTitle {
            get {
                return ResourceManager.GetString("AuthenticationEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, подождите....
        /// </summary>
        public static string AuthenticationProgressText {
            get {
                return ResourceManager.GetString("AuthenticationProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите с помощью своего аккаунта социальной сети.
        /// </summary>
        public static string AuthenticationTitle {
            get {
                return ResourceManager.GetString("AuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не могу определить текущее местоположение. Возможно, эта возможность заблокирована вами..
        /// </summary>
        public static string GetMyCurrentLocationError {
            get {
                return ResourceManager.GetString("GetMyCurrentLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в избранное.
        /// </summary>
        public static string MainPageAppBarFavoriteText {
            get {
                return ResourceManager.GetString("MainPageAppBarFavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на слои.
        /// </summary>
        public static string MainPageAppBarLayersText {
            get {
                return ResourceManager.GetString("MainPageAppBarLayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на где я.
        /// </summary>
        public static string MainPageAppBarLocationText {
            get {
                return ResourceManager.GetString("MainPageAppBarLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на поиск.
        /// </summary>
        public static string MainPageAppBarSearchText {
            get {
                return ResourceManager.GetString("MainPageAppBarSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на о программе.
        /// </summary>
        public static string MainPageMenuAbout {
            get {
                return ResourceManager.GetString("MainPageMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на моя учетная запись.
        /// </summary>
        public static string MainPageMenuAccount {
            get {
                return ResourceManager.GetString("MainPageMenuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на избранное.
        /// </summary>
        public static string MainPageMenuFavorite {
            get {
                return ResourceManager.GetString("MainPageMenuFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на история.
        /// </summary>
        public static string MainPageMenuHistory {
            get {
                return ResourceManager.GetString("MainPageMenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мои особые места.
        /// </summary>
        public static string MainPageMenuPlaces {
            get {
                return ResourceManager.GetString("MainPageMenuPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на метки рядом со мной.
        /// </summary>
        public static string MainPageMenuPoi {
            get {
                return ResourceManager.GetString("MainPageMenuPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оставить отзыв.
        /// </summary>
        public static string MainPageMenuRespect {
            get {
                return ResourceManager.GetString("MainPageMenuRespect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на настройки.
        /// </summary>
        public static string MainPageMenuSettings {
            get {
                return ResourceManager.GetString("MainPageMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мои треки.
        /// </summary>
        public static string MainPageMenuTracks {
            get {
                return ResourceManager.GetString("MainPageMenuTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ужасно ехать, плохо ходить.
        /// </summary>
        public static string PoiBadRoadDescription {
            get {
                return ResourceManager.GetString("PoiBadRoadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плохая дорога.
        /// </summary>
        public static string PoiBadRoadName {
            get {
                return ResourceManager.GetString("PoiBadRoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорожное наблюдение.
        /// </summary>
        public static string PoiCameraDescription {
            get {
                return ResourceManager.GetString("PoiCameraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камеры.
        /// </summary>
        public static string PoiCameraName {
            get {
                return ResourceManager.GetString("PoiCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорожное происшествие.
        /// </summary>
        public static string PoiCrashDescription {
            get {
                return ResourceManager.GetString("PoiCrashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авария.
        /// </summary>
        public static string PoiCrashName {
            get {
                return ResourceManager.GetString("PoiCrashName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать опции самому.
        /// </summary>
        public static string PoiCustomDescription {
            get {
                return ResourceManager.GetString("PoiCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моя метка.
        /// </summary>
        public static string PoiCustomName {
            get {
                return ResourceManager.GetString("PoiCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно поскользнуться.
        /// </summary>
        public static string PoiIceDescription {
            get {
                return ResourceManager.GetString("PoiIceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лёд.
        /// </summary>
        public static string PoiIceName {
            get {
                return ResourceManager.GetString("PoiIceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная метка.
        /// </summary>
        public static string PoiMistakeDescription {
            get {
                return ResourceManager.GetString("PoiMistakeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string PoiMistakeName {
            get {
                return ResourceManager.GetString("PoiMistakeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорожный патруль.
        /// </summary>
        public static string PoiPoliceDescription {
            get {
                return ResourceManager.GetString("PoiPoliceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менты.
        /// </summary>
        public static string PoiPoliceName {
            get {
                return ResourceManager.GetString("PoiPoliceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень большая лужа.
        /// </summary>
        public static string PoiPoolDescription {
            get {
                return ResourceManager.GetString("PoiPoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лужа.
        /// </summary>
        public static string PoiPoolName {
            get {
                return ResourceManager.GetString("PoiPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ремонтные работы.
        /// </summary>
        public static string PoiRepairsDescription {
            get {
                return ResourceManager.GetString("PoiRepairsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ремонт.
        /// </summary>
        public static string PoiRepairsName {
            get {
                return ResourceManager.GetString("PoiRepairsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        public static string PoiSelectionCustomName {
            get {
                return ResourceManager.GetString("PoiSelectionCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки метки.
        /// </summary>
        public static string PoiSelectionCustomTitle {
            get {
                return ResourceManager.GetString("PoiSelectionCustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать метку.
        /// </summary>
        public static string PoiSelectionTitle {
            get {
                return ResourceManager.GetString("PoiSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий:.
        /// </summary>
        public static string PoiSettingsComment {
            get {
                return ResourceManager.GetString("PoiSettingsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое описание:.
        /// </summary>
        public static string PoiSettingsCustomDescription {
            get {
                return ResourceManager.GetString("PoiSettingsCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все необходимые поля настроек заполнены.
        /// </summary>
        public static string PoiSettingsCustomEmptyError {
            get {
                return ResourceManager.GetString("PoiSettingsCustomEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмеченное на карте.
        /// </summary>
        public static string PoiSettingsMarkerSearchLocation {
            get {
                return ResourceManager.GetString("PoiSettingsMarkerSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мое местоположение.
        /// </summary>
        public static string PoiSettingsMyLocation {
            get {
                return ResourceManager.GetString("PoiSettingsMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указать место.
        /// </summary>
        public static string PoiSettingsSearchLocation {
            get {
                return ResourceManager.GetString("PoiSettingsSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставить метку.
        /// </summary>
        public static string PoiSettingsTitle {
            get {
                return ResourceManager.GetString("PoiSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорога перекрыта.
        /// </summary>
        public static string PoiStopAutoDescription {
            get {
                return ResourceManager.GetString("PoiStopAutoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проезда нет.
        /// </summary>
        public static string PoiStopAutoName {
            get {
                return ResourceManager.GetString("PoiStopAutoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тротуар перекрыт.
        /// </summary>
        public static string PoiStopWalkDescription {
            get {
                return ResourceManager.GetString("PoiStopWalkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не пройти.
        /// </summary>
        public static string PoiStopWalkName {
            get {
                return ResourceManager.GetString("PoiStopWalkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определение местоположения.
        /// </summary>
        public static string ProgressIndicatorCurrentLocationText {
            get {
                return ResourceManager.GetString("ProgressIndicatorCurrentLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-ru.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
